//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailClientRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailMessage()
        {
            this.EmailRecipients = new HashSet<EmailRecipient>();
        }
    
        public long ID { get; set; }
        public System.Guid UID { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public Nullable<long> EmailFolderTypeID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual EmailFolderType EmailFolderType { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailRecipient> EmailRecipients { get; set; }
    }
}
